import Head from 'next/head'
import HomePage from "../containers/home-page";
import { useEffect } from "react";

export default function LoginPage() {

    let access_token = ""
    useEffect(() => {
        // Perform localStorage action
        access_token = localStorage.getItem("access_token");
    }, [])
    if (!access_token) {

    }
    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.svg" />
            </Head>
            <HomePage />
        </>
    )
}