import Head from 'next/head'
import { Inter } from '@next/font/google'
import LandingContainer from '../containers/landing-page'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>JobHunt.id</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <LandingContainer />
    </>
  )
}
